change img file name to ass
GSG-FC03/Online-Learning-Team04 pull request #11
Opened 2021-06-24 21:26 UTC by farahalashi

relates #6

2021-06-24 21:29 UTC, salsabeelomar approved these changes

2021-06-24 21:47 UTC, Mosab-Ahmed requested changes
Change name to assets
And put sara in review

2021-06-25 08:33 UTC, sara219 requested changes
Change the dir name to assets, inside the dir create another dirs called (images, video, ...etc)

2021-06-25 08:41 UTC, Mosab-Ahmed reviewed
Close this withdrawal request
And create a new Issue to create an assets file with a new branch

2021-06-25 08:42 UTC, closed without merging