modified Readme file
GSG-FC03/Online-Learning-Team04 pull request #8
Opened 2021-06-23 18:02 UTC by Mosab-Ahmed

2021-06-23 18:27 UTC, sara219 requested changes

2021-06-23 18:27 UTC, sara219 commented on README.md
> +# Team 4: Online Learning
Delete the first title (the first line)

2021-06-23 18:28 UTC, sara219 requested changes

2021-06-23 18:28 UTC, sara219 commented on README.md
> +# Team 4: Online Learning
Delete the first title _(first line)_

2021-06-23 19:44 UTC, salsabeelomar approved these changes, later dismissed

2021-06-23 19:47 UTC, farahalashi reviewed
100%

2021-06-24 13:54 UTC, sara219 approved these changes

2021-06-24 17:40 UTC, farahalashi approved these changes

2021-06-24 17:44 UTC, NadaSaleh20 approved these changes

2021-06-24 17:44 UTC, salsabeelomar approved these changes

2021-06-24 17:45 UTC, merged